name: release

on: 
  workflow_dispatch: 

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Set context
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: use Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Install dependencies
        run: yarn
        working-directory: ./src/core
      - name: Install dependencies
        run: yarn
        working-directory: ./src/app-ui
      - name: build
        run: yarn build
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            dist/*.dmg
            dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
